// Copyright (C) 2025 FuseCP
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuseCP.Portal.ProviderControls {
    
    public partial class Bind_Settings {
        protected System.Web.UI.WebControls.Label lblIPAddresses;
        protected FuseCP.Portal.ProviderControls.Common_IPAddressesList iPAddressesList;
        protected System.Web.UI.WebControls.Label lblAllowZoneTransfers;
        protected System.Web.UI.WebControls.TextBox txtAllowZoneTransfers;
        protected System.Web.UI.WebControls.Label lblResponsiblePerson;
        protected System.Web.UI.WebControls.TextBox txtResponsiblePerson;
        protected System.Web.UI.WebControls.Label lblBindConfigPath;
        protected System.Web.UI.WebControls.TextBox txtBindConfigPath;
        protected System.Web.UI.WebControls.Label lblZonesFolderPath;
        protected System.Web.UI.WebControls.TextBox txtZonesFolderPath;
        protected System.Web.UI.WebControls.Label lblZoneFileNameTemplate;
        protected System.Web.UI.WebControls.TextBox txtZoneFileNameTemplate;
        protected System.Web.UI.WebControls.Label lblBindReloadBatch;
        protected System.Web.UI.WebControls.TextBox txtBindReloadBatch;
        protected System.Web.UI.WebControls.Label lblRefreshInterval;
        protected FuseCP.Portal.ScheduleInterval intRefresh;
        protected System.Web.UI.WebControls.Label lblRetryInterval;
        protected FuseCP.Portal.ScheduleInterval intRetry;
        protected System.Web.UI.WebControls.Label lblExpireLimit;
        protected FuseCP.Portal.ScheduleInterval intExpire;
        protected System.Web.UI.WebControls.Label lblMinimumTtl;
        protected FuseCP.Portal.ScheduleInterval intTtl;
        protected System.Web.UI.WebControls.Label lblSecondaryDNS;
        protected FuseCP.Portal.ProviderControls.Common_SecondaryDNSServers secondaryDNSServers;
        protected System.Web.UI.WebControls.Label lblNameServers;
        protected FuseCP.Portal.UserControls.EditDomainsList nameServers;
    }
}
