// Copyright (C) 2025 FuseCP
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuseCP.Portal.ProviderControls {
    
    public partial class hMailServer_EditAccount {
        protected FuseCP.Portal.CollapsiblePanel secAutoresponder;
        protected System.Web.UI.WebControls.Panel AutoresponderPanel;
        protected System.Web.UI.WebControls.Label lblResponderEnabled;
        protected System.Web.UI.WebControls.CheckBox chkResponderEnabled;
        protected System.Web.UI.WebControls.Label lblSubject;
        protected System.Web.UI.WebControls.TextBox txtSubject;
        protected System.Web.UI.WebControls.Label lblMessage;
        protected System.Web.UI.WebControls.TextBox txtMessage;
        protected FuseCP.Portal.CollapsiblePanel secForwarding;
        protected System.Web.UI.WebControls.Panel ForwardingPanel;
        protected System.Web.UI.WebControls.Label lblForwardTo;
        protected System.Web.UI.WebControls.TextBox txtForward;
    }
}
