// Copyright (C) 2025 FuseCP
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuseCP.Portal.ProviderControls {
    
    public partial class SmarterStats_Settings {
        protected System.Web.UI.WebControls.Label lblSmarterUrl;
        protected System.Web.UI.WebControls.TextBox txtSmarterUrl;
        protected System.Web.UI.WebControls.Label lblUsername;
        protected System.Web.UI.WebControls.TextBox txtUsername;
        protected System.Web.UI.WebControls.Label lblPassword;
        protected System.Web.UI.WebControls.TextBox txtPassword;
        protected System.Web.UI.WebControls.Label lblServer;
        protected System.Web.UI.WebControls.DropDownList ddlServers;
        protected System.Web.UI.WebControls.Label lblLogFormat;
        protected System.Web.UI.WebControls.DropDownList ddlLogFormat;
        protected System.Web.UI.WebControls.Label lblLogWildcard;
        protected System.Web.UI.WebControls.TextBox txtLogWilcard;
        protected System.Web.UI.WebControls.Label lblLogAutoDeletion;
        protected System.Web.UI.WebControls.TextBox txtLogDeleteDays;
        protected System.Web.UI.WebControls.Label lblDontDelete;
        protected System.Web.UI.WebControls.Label lblSmarterLogs;
        protected System.Web.UI.WebControls.TextBox txtSmarterLogs;
        protected System.Web.UI.WebControls.Label lblSmarterLogAutoDeletion;
        protected System.Web.UI.WebControls.TextBox txtSmarterLogDeleteMonths;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label lblTimeZone;
        protected FuseCP.Portal.TimeZones timeZone;
        protected System.Web.UI.WebControls.Label lblBuildUncLogsPath;
        protected System.Web.UI.WebControls.CheckBox chkBuildUncLogsPath;
        protected System.Web.UI.WebControls.Label lblStatsUrl;
        protected System.Web.UI.WebControls.TextBox txtStatsUrl;
    }
}
