// Copyright (C) 2025 FuseCP
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuseCP.Portal {
    
    public partial class SpaceDetailsHeaderControl {
        protected System.Web.UI.WebControls.Literal litPackageName;
        protected System.Web.UI.WebControls.Label lblUser;
        protected FuseCP.Portal.UserDetails spaceUser;
        protected System.Web.UI.WebControls.Label lblHostingPlan;
        protected System.Web.UI.WebControls.Literal litHostingPlan;
        protected System.Web.UI.HtmlControls.HtmlTableRow rowSpaceServer;
        protected System.Web.UI.WebControls.Label lblTargetServer;
        protected FuseCP.Portal.ServerDetails serverDetails;
        protected System.Web.UI.WebControls.Label lblCreationDate;
        protected System.Web.UI.WebControls.Literal litPurchaseDate;
        protected System.Web.UI.HtmlControls.HtmlTableRow rowStatus;
        protected System.Web.UI.WebControls.Label lblStatus;
        protected System.Web.UI.WebControls.Literal litStatus;
    }
}
