#!/bin/sh
rm /usr/share/fusecp/Installer/Setup2.*

echo "===================================================================="
echo "run 'sudo fusecp-installer' to complete the installation of FuseCP"
echo "===================================================================="

